sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gauri-sd/travis-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true gauri-sd/travis-demo npm run test
